name: rspec

on:
  [push]

env:
  RACK_ENV: test

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ruby-version: 3.3
          - ruby-version: 3.2
          - ruby-version: 3.1
          - ruby-version: 3.0.7
          - ruby-version: 2.7

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Update bundler
        run: gem update --system 3.4.22 && bundle update --bundler
      - name: Run tests
        run: bundle exec rspec
      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          rubocop_extensions: ''
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check

